# As of October 2024, the use of the esphome dev build is mandatory for bluetooth to compile correctly

esphome:
  name: m5env
  friendly_name: M5Env

# M5Stack NanoC6 Dev Kit
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # https://docs.espressif.com/projects/esp-matter/en/latest/esp32c6/developing.html#flashing-the-firmware
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  
  # https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
  on_connect:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

# Bluetooth Proxy
esp32_ble_tracker:
 scan_parameters:
  continuous: false
bluetooth_proxy:
  active: true
  
i2c:
  sda: 2
  scl: 1
  # https://github.com/esphome/esphome/discussions/6957#discussioncomment-10099453
  scan: false

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: "temperature"
    humidity:
      name: "Humidity"
      id: "humidity"
    address: 0x44
  - platform: bmp280_i2c
    pressure:
      name: "Pressure"
      id: "pressure"
    address: 0x76